# VelocityDiscordWhitelist Configuration Example
# Copy this file to src/main/resources/config.yaml and customize for your setup

# Database Configuration
database:
  host: "localhost"
  port: 3306
  database: "discord_whitelist"
  table: "whitelist"
  username: "your_username"
  password: "your_password"

# Discord Bot Configuration
discord:
  enabled: true  # Set to false to disable Discord integration entirely
  token: "YOUR_BOT_TOKEN_HERE"
  guild_id: "YOUR_GUILD_ID_HERE"
  verification_channel: "YOUR_VERIFICATION_CHANNEL_ID_HERE"
  init_timeout: 30
  roles:
    admin: "YOUR_ADMIN_ROLE_ID_HERE"
    verified: "YOUR_VERIFIED_ROLE_ID_HERE"

# Plugin Settings
settings:
  debug: false
  use_purgatory: true
  purgatory_server: "lobby"
  allow_reconnect: true
  max_verification_attempts: 3

# Purgatory Configuration
purgatory:
  session_timeout_minutes: 30

# Session Configuration
session:
  timeout: 15

# Geyser Integration (for Bedrock Edition support)
geyser:
  enabled: false
  handle_bedrock_players: true
  auto_verify_bedrock: false
  prefix: "."

# Vault Integration (Economy and Permissions)
vault:
  economy:
    enabled: false
    whitelist_reward: 100.0
    rank_progression_reward: 50.0
    rank_base_reward: 500
    subrank_multiplier: 0.5
    mainrank_multiplier: 2.0
  permissions:
    enabled: false
  reward_server: "survival"

# LuckPerms Integration
luckperms:
  enabled: false
  default_group: "verified"
  managed_groups:
    - "bystander"
    - "onlooker"
    - "wanderer"
    - "traveller"
    - "explorer"
    - "verified"
  discord_role_mappings:
    "YOUR_DISCORD_ROLE_ID_1": "luckperms-group-1"
    "YOUR_DISCORD_ROLE_ID_2": "luckperms-group-2"
  rank_mappings:
    "rank_1_0": "bystander"
    "rank_1_1": "onlooker"
    "rank_2_0": "wanderer"
    "rank_2_1": "traveller"
    "rank_3_0": "explorer"
    "rank_3_1": "verified"
  discord_mappings:
    "YOUR_SPECIAL_DISCORD_ID": "special_group"

# Rewards Configuration
rewards:
  enabled: true

# Ranks Configuration based on correct_rank_system.md
ranks:
  enabled: true
  main_ranks:
    - "bystander"
    - "onlooker" 
    - "wanderer"
    - "traveller"
    - "explorer"
    - "adventurer"
    - "surveyor"
    - "navigator"
    - "journeyman"
    - "pathfinder"
    - "trailblazer"
    - "pioneer"
    - "craftsman"
    - "specialist"
    - "artisan"
    - "veteran"
    - "sage"
    - "luminary"
    - "titan"
    - "legend"
    - "eternal"
    - "ascendant"
    - "celestial"
    - "divine"
    - "deity"
  sub_ranks:
    - "novice"
    - "apprentice"
    - "adept"
    - "master"
    - "heroic"
    - "mythic"
    - "immortal"
  starting_rank:
    main: "bystander"
    sub: "novice"
  progression:
    xp_per_subrank: 1000
    xp_multiplier_per_main_rank: 1.5

# XP System Configuration
xp:
  enabled: true
  rate_limiting:
    enabled: true
    maxEventsPerMinute: 10
    maxEventsPerHour: 100
    maxEventsPerDay: 500
    cooldownSeconds: 5
  modifiers:
    advancement: 1.0
    playtime: 0.5
    kill: 0.8
    break_block: 0.3
    place_block: 0.2
    craft_item: 0.4
    enchant_item: 1.2
    trade: 0.6
    fishing: 0.4
    mining: 0.3

# Integrations Configuration
integrations:
  # BlazeAndCaves Advancement Pack Integration
  blazeandcaves:
    enabled: false  # Set to true to enable BlazeAndCaves integration
    achievements_file: "blazeandcaves-achievements.json"
    auto_detect: true  # Automatically detect when BlazeAndCaves pack is loaded
    xp_multipliers:
      easy: 1.0
      medium: 1.25
      hard: 1.5
      insane: 2.0
      extreme: 3.0
    variant_bonuses:
      terralith: 0.1  # +10% bonus for Terralith achievements
      hardcore: 0.5   # +50% bonus for hardcore achievements
    rewards:
      enabled: true
      give_items: true      # Whether to give item rewards from achievements
      give_trophies: true   # Whether to give trophy rewards
      announce: true        # Whether to announce achievements in chat

# Messages Configuration
messages:
  prefix: "&8[&bWhitelist&8]&r "
  verification_code: "Your verification code is: %code%"
  verification_success: "Verification successful! Welcome to the server!"
  verification_failed: "Verification failed. Please try again."
  session_expired: "Your verification session has expired. Please request a new code."
  already_verified: "You are already verified on this server."
  purgatory_message: "You are in purgatory mode. Please verify your Discord account to continue."
  invalid_code: "Invalid verification code. Please check and try again."
  max_attempts_exceeded: "Maximum verification attempts exceeded. Please request a new code."
  discord_link_success: "Your Discord account has been successfully linked!"
  discord_already_linked: "Your Discord account is already linked to another player."
  not_whitelisted: "&cYou are not whitelisted on this server!"
  no_permission: "&cYou don't have permission to use this command!"
  whitelist_added: "&aYou have been whitelisted!"
  whitelist_removed: "&cYou have been removed from the whitelist!"
  already_whitelisted: "&eYou are already whitelisted!"
  player_not_found: "&cPlayer not found!"
  discord_user_not_found: "Discord user not found."
  command_usage: "Usage: %usage%"
  reload_success: "Configuration reloaded successfully!"
  reload_failed: "Failed to reload configuration. Check console for errors."
  database_error: "A database error occurred. Please try again later."
  permission_denied: "You do not have permission to use this command."
