# ==========================================================================
# VelocityDiscordWhitelist Plugin - Example Configuration
# Version: 1.3.1
# 
# This is a comprehensive example showing all available configuration options.
# Copy this to config.yaml and customize for your server setup.
# ==========================================================================

# ==========================================
# CORE SETTINGS
# ==========================================

# Master switch for the entire plugin
enabled: true

# General configuration
general:
  # Enable debug logging for troubleshooting
  debug: false
  
  # Session timeout for verification process
  session:
    timeout:
      minutes: 30

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

database:
  # Supported types: mysql, mariadb, postgresql, sqlite
  type: mysql
  
  # Connection retry settings
  retry_count: 3
  retry_delay: 5000  # milliseconds
  
  # SQLite Configuration (used as fallback)
  sqlite:
    file_path: "plugins/velocitydiscordwhitelist/whitelist.db"
  
  # MySQL/MariaDB Configuration
  mysql:
    host: localhost
    port: 3306
    database: velocity_whitelist
    user: velocity_user
    password: your_secure_password_here
    use_ssl: true
    
    # HikariCP connection pool settings
    connection_pool:
      maximum_pool_size: 10
      minimum_idle: 5
      connection_timeout: 30000
      idle_timeout: 600000
      max_lifetime: 1800000
    
    # Table configuration
    tables:
      whitelist: "whitelist"
      players: "players"
      rank_progression: "rank_progression"
      verification_sessions: "verification_sessions"

# ==========================================
# DISCORD INTEGRATION
# ==========================================

discord:
  enabled: true
  
  # Bot authentication
  token: 'YOUR_DISCORD_BOT_TOKEN_HERE'
  
  # Server and channel configuration
  server_id: '123456789012345678'  # Your Discord server/guild ID
  approved_channel_ids: '987654321098765432,876543210987654321'  # Comma-separated channel IDs
  
  # Connection settings
  init_timeout: 30  # seconds to wait for Discord connection
  
  # Feature toggles
  features:
    verification: true      # Enable Discord-based verification
    rank_sync: true        # Sync Discord roles with in-game ranks
    notifications: true    # Send Discord notifications for events
    commands: true         # Enable Discord commands (/connectme, /verify)

# ==========================================
# VAULT INTEGRATION
# ==========================================

vault:
  enabled: true
  
  # Economy integration
  economy:
    enabled: true
    
    # Reward amounts
    whitelist_reward: 1000        # Currency given when first whitelisted
    rank_base_reward: 500         # Base currency for rank progression
    subrank_multiplier: 0.5       # Multiplier for sub-rank rewards
    mainrank_multiplier: 2.0      # Multiplier for main rank rewards
  
  # Permission integration
  permissions:
    enabled: true
    
    # Group management
    default_group: "verified"     # Default group for whitelisted players
    
    # Rank-based group mappings (rank_level -> group_name)
    rank_groups:
      "1": "bronze"
      "2": "silver"
      "3": "gold"
      "4": "platinum"
      "5": "diamond"
      "1.1": "bronze_plus"
      "2.1": "silver_plus"
      "3.1": "gold_plus"
      "4.1": "platinum_plus"
      "5.1": "diamond_plus"
  
  # Server where rewards are applied
  reward_server: "survival"

# ==========================================
# LUCKPERMS INTEGRATION
# ==========================================

luckperms:
  enabled: true
  
  # Default group for whitelisted players
  default_group: "verified"
  
  # Rank progression group mappings
  rank_mappings:
    "1": "bronze"
    "2": "silver" 
    "3": "gold"
    "4": "platinum"
    "5": "diamond"
    "1.1": "bronze_plus"
    "2.1": "silver_plus"
    "3.1": "gold_plus"
    "4.1": "platinum_plus"
    "5.1": "diamond_plus"
  
  # Discord role to permission group mappings
  discord_mappings:
    "Moderator": "moderator"
    "Admin": "admin"
    "VIP": "vip"
    "Supporter": "supporter"
    "Builder": "builder"
    "Helper": "helper"
  
  # Group priority for determining primary group (higher = more important)
  group_priorities:
    "owner": 1000
    "admin": 100
    "moderator": 90
    "helper": 85
    "vip": 80
    "diamond_plus": 75
    "diamond": 70
    "platinum_plus": 65
    "platinum": 60
    "gold_plus": 55
    "gold": 50
    "silver_plus": 45
    "silver": 40
    "bronze_plus": 35
    "bronze": 30
    "verified": 20
    "default": 10

# ==========================================
# REWARDS AND PROGRESSION
# ==========================================

rewards:
  enabled: true
  
  # Rank progression system
  progression:
    enabled: true
    
    # XP requirements for ranks (cumulative)
    rank_requirements:
      1: 0      # Bronze (starting rank)
      2: 1000   # Silver
      3: 3000   # Gold  
      4: 6000   # Platinum
      5: 10000  # Diamond
    
    # Sub-rank progression within main ranks
    subrank_requirements:
      base_xp: 500        # XP needed for first sub-rank
      multiplier: 1.5     # Multiplier for subsequent sub-ranks
  
  # Achievement system
  achievements:
    enabled: true
    
    # Achievement definitions loaded from achievements.json
    # This includes milestones, special events, etc.
  
  # Reward delivery
  delivery:
    # How rewards are given to players
    method: "auto"        # auto, manual, or command
    
    # Notification settings
    notifications:
      discord: true       # Notify in Discord
      in_game: true       # Notify in-game when player joins

# ==========================================
# GEYSER/BEDROCK SUPPORT
# ==========================================

geyser:
  enabled: true
  prefix: '.'  # Prefix used for Bedrock usernames

# ==========================================
# VERIFICATION SETTINGS
# ==========================================

validation:
  # Account verification options
  mojang_verification: true     # Verify Java accounts through Mojang
  geyser_verification: true     # Verify Bedrock accounts through Geyser
  
  # Verification process settings
  timeout: 5                    # Minutes before verification expires
  code_format: '***-***'        # Format pattern for verification codes
  
  # Purgatory system
  purgatory:
    enabled: true
    server: "lobby"             # Server where unverified players wait
    max_sessions: 100           # Maximum concurrent verification sessions

# ==========================================
# SERVER SETTINGS
# ==========================================

servers:
  # Default server for new/unverified players
  lobby_server: "lobby"
  
  # Server where main gameplay happens
  main_server: "survival"
  
  # Server-specific whitelist rules
  per_server_whitelist: false

# ==========================================
# MESSAGES AND NOTIFICATIONS
# ==========================================

messages:
  # Player-facing messages
  not_whitelisted: "Sorry, you are not whitelisted. Please visit our Discord to gain access."
  verification_expired: "Your verification session has expired. Please try again."
  verification_success: "Welcome! You have been successfully whitelisted."
  rank_up: "Congratulations! You've reached rank {rank}!"
  
  # Discord messages
  discord:
    verification_start: "Verification started for {player}. Code: {code}"
    verification_complete: "Player {player} has been successfully verified!"
    rank_progression: "{player} has progressed to rank {rank}!"

# ==========================================
# ADVANCED FEATURES
# ==========================================

advanced:
  # Performance settings
  cache:
    enabled: true
    ttl_minutes: 15             # Cache timeout in minutes
    max_entries: 1000           # Maximum cached entries
  
  # Metrics and monitoring
  metrics:
    enabled: true               # Enable bStats metrics
    custom_charts: true         # Include custom metric charts
  
  # API integration
  api:
    enabled: false              # Enable REST API for external integrations
    port: 8080                  # API server port
    auth_token: ""              # API authentication token
  
  # Backup and maintenance
  backup:
    enabled: false              # Auto-backup of database
    interval_hours: 24          # Hours between backups
    retention_days: 7           # Days to keep backups
